export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_PROPERTY_DETAILS = 'SET_PROPERTY_DETAILS';

